mogrify -resize 25% scene_1.png
mogrify -resize 25% scene_2.png
mogrify -resize 25% scene_3.png
mogrify -resize 25% scene_4.png
mogrify -resize 25% scene_5.png
mogrify -resize 25% scene_6.png
mogrify -resize 25% scene_7.png
mogrify -resize 25% scene_8.png
mogrify -resize 25% scene_9.png
mogrify -resize 25% scene_A.png
mogrify -resize 25% scene_B.png
mogrify -resize 25% scene_C.png
mogrify -resize 25% scene_D.png
mogrify -resize 25% scene_E.png
mogrify -resize 25% scene_F.png
mogrify -resize 25% scene_G.png
mogrify -resize 25% scene_H.png
mogrify -resize 25% scene_I.png
mogrify -resize 25% scene_J.png
