mogrify -resize 50% scene_F1.png
mogrify -resize 50% scene_F2.png
mogrify -resize 50% scene_F3.png
mogrify -resize 50% scene_F4.png
mogrify -resize 50% scene_F5.png
mogrify -resize 50% scene_F6.png
mogrify -resize 50% scene_F7.png
mogrify -resize 50% scene_F8.png
mogrify -resize 50% scene_F9.png
mogrify -resize 50% scene_F9a.png
mogrify -resize 50% scene_F9b.png
